default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: password
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>

development:
  <<: *default
  database: ethereum_explorer_development

test:
  <<: *default
  database: ethereum_explorer_test

production:
  <<: *default
  database: ethereum_explorer_production
  # Use read replicas
  replica:
    <<: *default
    database: ethereum_explorer_production
    host: <%= ENV.fetch("DB_REPLICA_HOST", "localhost") %>
    replica: true
