default: &default
  adapter: <%= ENV.fetch('DATABASE_ADAPTER', 'mysql2') %>
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 6).to_i * ENV.fetch("WEB_CONCURRENCY", 1).to_i %>
  reconnect: true
  host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('DATABASE_PORT', 3306) %>
  username: <%= ENV.fetch('DATABASE_USER', 'root') %>
  password: <%= ENV.fetch('DATABASE_PASS', '') %>

development:
  <<: *default
  database: oauth_development

test:
  <<: *default
  database: oauth_test

production:
  <<: *default
  <% if ENV['DATABASE_REPLICA_ENABLED'] == 'true' %>
  makara:
    # the following are for the master slave
    blacklist_duration: 5
    master_ttl: 1
    master_strategy: round_robin
    sticky: false
    connections:
      - role: master
        host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
        database: <%= ENV.fetch('DATABASE_NAME', 'oauth_production') %>
        port: <%= ENV.fetch('DATABASE_PORT', 3306) %>
        username: <%= ENV.fetch('DATABASE_USER', 'root') %>
        password: <%= ENV['DATABASE_PASS'] %>
        blacklist_duration: 5

      - role: slave
        host: <%= ENV.fetch('DATABASE_SLAVE_HOST', '127.0.0.1') %>
        database: <%= ENV.fetch('DATABASE_NAME', 'oauth_production') %>
        port: <%= ENV.fetch('DATABASE_SLAVE_PORT', 3306) %>
        username: <%= ENV.fetch('DATABASE_SLAVE_USER', 'root') %>
        password: <%= ENV['DATABASE_SLAVE_PASS'] %>

<% if ENV['DATABASE_REPLICA2_ENABLED'] == 'true' %>
      - role: slave2
        host: <%= ENV.fetch('DATABASE_SLAVE2_HOST', '127.0.0.1') %>
        database: <%= ENV.fetch('DATABASE_NAME', 'oauth_production') %>
        port: <%= ENV.fetch('DATABASE_SLAVE_PORT', 3306) %>
        username: <%= ENV.fetch('DATABASE_SLAVE_USER', 'root') %>
        password: <%= ENV['DATABASE_SLAVE_PASS'] %>
<% end %>

  <% else %>
  database: <%= ENV.fetch('DATABASE_NAME', 'oauth_production') %>
  <% end %>
