#
# email and level are required for users
#
# permissions defines user roles and abilities
users:
  - email: <%= ENV.fetch("ADMIN_EMAIL", "admin@barong.io") %>
    password: <%= ENV.fetch("ADMIN_PASSWORD", nil) %>
    role: "admin"
    state: "active"
    level: 1

levels:
  - key: email
    value: verified
    description: "User clicked on the confirmation link"
  - key: phone
    value: verified
    description: "User entered a valid code from sms"
  - key: document
    value: verified
    description: "User personal documents have been verified"

restrictions:
  - { category: whitelist, scope: country, value: UA, state: disabled }
  - { category: maintenance, scope: all, value: all, state: disabled }
  - { category: blacklist, scope: ip, value: 164.116.47.255, state: disabled, code: 433 }
  - { category: blacklist, scope: ip_subnet, value: 164.116.47.0/24, state: disabled, code: 434 }
  - { category: blacklist, scope: country, value: USA, state: disabled, code: 435 }
  - { category: blacklist, scope: continent, value: SA, state: disabled, code: 436 }

permissions:
 # SUPER ADMIN has an access to the whole system without any limits
 # so we can just grant him access to /api/v2/*
 - { role: superadmin, verb: all, path: api/v2, action: accept }
 # Rango(ranger) access
 - { role: superadmin, verb: get, path: api/v2/ranger, action: accept }
 # we are watching after you 0_0
 - { role: superadmin, verb: post, path: api/v2/, action: audit }
 - { role: superadmin, verb: put, path: api/v2/, action: audit }
 - { role: superadmin, verb: delete, path: api/v2/, action: audit }

# ADMIN
# admin has nearly full access to barong and peatio api, except managing permissions
 - { role: admin, verb: all, path: api/v2, action: accept }

 # ranger access
 - { role: admin, verb: get, path: api/v2/ranger, action: accept }
 # Finex upstream access
 - { role: admin, verb: get, path: api/v2/open_finance, action: accept }
 # admin doesnt have access to manage platform roles and permissions
 - { role: admin, verb: all, path: api/v2/barong/admin/permissions, action: drop }
 # admin doesnt have access to manage roles
 - { role: admin, verb: all, path: api/v2/barong/admin/users/role, action: drop }
 # admin doesnt have access to admin activities
 - { role: admin, verb: all, path: api/v2/barong/admin/activities/admin, action: drop }
 # we are watching after you 0_0
 - { role: admin, verb: post, path: api/v2/, action: audit }
 - { role: admin, verb: put, path: api/v2/, action: audit }
 - { role: admin, verb: delete, path: api/v2/, action: audit }

 # retailer
 # has standard user permissions to ACCOUNT, MARKET, RESOURCE modules
 - { role: retailer, verb: all, path: api/v2/barong/resource, action: accept }
 - { role: retailer, verb: all, path: api/v2/resource, action: accept }
 - { role: retailer, verb: all, path: api/v2/barong/swagger, action: accept}

 # institution
 # has standard user permissions to ACCOUNT, MARKET, RESOURCE modules
 - { role: institution, verb: all, path: api/v2/barong/resource, action: accept }
 - { role: institution, verb: all, path: api/v2/resource, action: accept }
 - { role: institution, verb: all, path: api/v2/barong/swagger, action: accept}

 # issuer
 # has standard user permissions to ACCOUNT, MARKET, RESOURCE modules
 - { role: issuer, verb: all, path: api/v2/barong/resource, action: accept }
 - { role: issuer, verb: all, path: api/v2/resource, action: accept }
 - { role: issuer, verb: all, path: api/v2/barong/swagger, action: accept}

 # MOCK
 - { role: mock, verb: all, path: api/v2/peatio/account, action: accept }
 - { role: mock, verb: all, path: api/v2/peatio/market, action: accept }
 - { role: mock, verb: all, path: api/v2/finex/market, action: accept }
 - { role: mock, verb: all, path: api/v2/barong/resource, action: accept }
 # ranger access
 - { role: mock, verb: get, path: api/v2/ranger, action: accept }
 # Finex upstream access
 - { role: mock, verb: get, path: api/v2/open_finance, action: accept }
 # applogic access
 - { role: mock, verb: all, path: api/v2/applogic, action: accept }

platform_settings:
 - service_key: mock
   service_name: Mock Verify Service
   service_type: sms
 - service_key: twilio_sms
   service_name: Twilio SMS Service
   service_type: sms
 - service_key: twilio_verify
   service_name: Twilio Verify Service
   service_type: sms
 - service_key: aws_sns
   service_name: AWS SNS Service
   service_type: sms
 - service_key: bulkgate
   service_name: Bulkgate SMS Service
   service_type: sms
 - service_key: smsala
   service_name: SMSala SMS Service
   service_type: sms
 - service_key: sendgrid
   service_name: Sendgrid
   service_type: email
 - service_key: mock
   service_name: Mock Email Verify Service
   service_type: email

country_services:
 - country_code: all
   country_name: all
   continent: all
   service_type: email
 - country_code: all
   country_name: all
   continent: all
   service_type: sms
